### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by eloiup** [sebinsua/scrape-twitter#10]
vi eddited ~/,scrape-twitter

added:

```
TWITTER_USERNAME = 'username'
TWITTER_PASSWORD = 'password'
```

tried sample command:

`scrape-twitter likes sebinsua ###(or another random account)
`
receive following error msg:

> Error: An active login is required for this API call
    at checkStatus (/usr/local/lib/node_modules/scrape-twitter/dist/lib/query.js:11:17)
    at process._tickCallback (node.js:368:9)

login shld have been succesfull (if i try same account with a wrong password i get a wrong password/username error)
how to proceed? ty

**Comment by sebinsua** [comment]
It works for me. However, the syntax within my `~/.scrape-twitter` is actually more like:

```sh
TWITTER_USERNAME=username
TWITTER_PASSWORD=password
TWITTER_KDT=blahblahblah
```

**Comment by taylorbrooks** [comment]
I'm getting the same error. 

Where do you get the KDT?

**Comment by gabidi** [comment]
Yeah i can't get login to work too.. Any help would be appreciated.

**Comment by rbeer** [comment]
Same issue, same solution. All my login fails (4 times, so far) were due to Twitter's bot detection kicking in, prompting to solve a Google Captcha. Not having a proper email address or a mobile number associated with the account might be another reason. In any case, logging in via app or web UI should be the first step of troubleshooting and even solve most instances.

I'd assume that there's ways to distinguish that from the server's response and give a warning accordingly. Haven't looked into it, though. Still fixing based on what we need, first. :)
