### ISSUE TITLE
Hexadecimal handles are converted to decimal numbers before scraping

### ISSUE THREAD

**Issue by 0x70b1a5** [sebinsua/scrape-twitter#2]
Steps to reproduce:
```
scrape-twitter profile [0xdeadbade, 0xabad1dea, ...] 
```

Stack trace: 
```
/usr/lib/node_modules/scrape-twitter/dist/lib/cli-utils.js:11
  return (username || '').replace('@', '');
                          ^

TypeError: (username || "").replace is not a function
    at Object.parseUsername (/usr/lib/node_modules/scrape-twitter/dist/lib/cli-utils.js:11:27)
    at Object.<anonymous> (/usr/lib/node_modules/scrape-twitter/dist/bin/scrape-twitter-profile.js:16:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/scrape-twitter/bin/scrape-twitter-profile.js:4:1)
```

I've traced the culprit code to [this line](https://github.com/substack/minimist/blob/master/index.js#L233) in [`minimist`](https://github.com/substack/minimist/):
```js
    for (var i = 0; i < args.length; i++) {
        var arg = args[i];
        
        if (/^--.+=/.test(arg)) {
            // ...
        }
        else {
            if (!flags.unknownFn || flags.unknownFn(arg) !== false) {
                argv._.push(
                    flags.strings['_'] || !isNumber(arg) ? arg : Number(arg) // Bingo
                );
            }
    // ...
    }

// ... snip ...

function isNumber (x) {
    if (typeof x === 'number') return true;
    if (/^0x[0-9a-f]+$/i.test(x)) return true; // Bingo II: This Time, It's Hecadecimal
    return /^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(e[-+]?\d+)?$/.test(x);
}
```

Unsure if I should file this issue there or here.

**Comment by sebinsua** [comment]
I should be able to fix this by [forcing it to consider the username as a string](https://github.com/substack/minimist#var-argv--parseargsargs-opts). Wait a mo.

**Comment by sebinsua** [comment]
Should be fixed now?
