### ISSUE TITLE
fetchCookie(url, opts) throws unexpected token function

### ISSUE THREAD

**Issue by nnnnicholas** [sebinsua/scrape-twitter#25]
Hello, I just downloaded `scrape-twitter `and am using it for the first time. I am experiencing an error. Apologies if this is a newbie mistake on my part :

Every scrape command I issue returns this result 
```
/root/.nvm/versions/node/v6.11.5/lib/node_modules/scrape-twitter/node_modules/fetch-cookie/index.js:11
  async function fetchCookie (url, opts) {
        ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.11.5/lib/node_modules/scrape-twitter/dist/lib/twitter-login.js:10:28
```

It shouldn't matter for `$ scrape-twitter profile ...` and `$ scrape-twitter conversation` commands, but I have set my environment variables for TWITTER_USERNAME and TWITTER_PASSWORD. The application crashes as above before Twitter responds with a KDT, if I understand the documentation correctly.

**Comment by zgruza** [comment]
Have same issue here.
Did you already solve this problem?

**Comment by nnnnicholas** [comment]
Nope I gave up.
