### ISSUE TITLE
Undefined profile output and timeline error

### ISSUE THREAD

**Issue by CookidNA** [sebinsua/scrape-twitter#34]
Getting these responses for profile and timeline (havent tested other commands just these two)

scrape-twitter profile sebinsua:
`
{
  "screenName": "",
  "name": "",
  "bio": "",
  "userMentions": [],
  "hashtags": [],
  "urls": [],
  "location": "",
  "joinDate": "undefined-undefined-01T00:00:00.000Z",
  "tweetCount": 0,
  "followingCount": 0,
  "followerCount": 0,
  "likeCount": 0
}`

scrape-twitter timeline nouswaves:

```
`invalid json response body at https://twitter.com/i/profiles/show/nouswaves/timeline?include_available_features=1&include_entities=1 reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://twitter.com/i/profiles/show/nouswaves/timeline?include_available_features=1&include_entities=1 reason: Unexpected token < in JSON at position 0
    at C:\Users\cooki\Desktop\bot\node_modules\scrape-twitter\node_modules\node-fetch\lib\body.js:48:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

    Access Twitter data without an API key.

    Usage
      $ scrape-twitter <command>

    Commands
      profile       Get a user's profile.
      timeline      Get a user's timeline.
      likes         Get a user's likes.
      connections   Get a user's connections.
      conversation  Get a particular conversation.
      list          Get the timeline of a particular list.
      search        Query Twitter for matching tweets.`
```

idk but these look like accessing twitter issues. Does this project still work?

**Comment by zgruza** [comment]
Looks like this project is Deprecated need to wait for Update. :/
